version: '3.0'

services:
  grafana:
    container_name: 'needleinajaystack-haystack-datasource'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-10.3.5}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/needleinajaystack-haystack-datasource
      - ./provisioning:/etc/grafana/provisioning
  haxall:
    image: "needleinajaystack/haxall:latest"
    environment:
      - SU_USER=su
      - SU_PASS=su
    ports:
      - 8080:8080/tcp
    volumes:
      - ~/haxall/proj:/opt/haxall/proj
