services:
  grafana:
    user: root
    container_name: 'needleinajaystack-haystack-datasource'

    platform: 'linux/amd64'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.3.3}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3000:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - "apparmor:unconfined"
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./dist:/var/lib/grafana/plugins/needleinajaystack-haystack-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/needleinajaystack-haystack-datasource

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.needleinajaystack-haystack-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: needleinajaystack-haystack-datasource
